name: IAV-analysis
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.7
 - seaborn=0.11
 - matplotlib=3.5
 - numpy=1.21
 - pandas=1.3
 - scipy=1.7
 - r-essentials=4.1
 - r-base=4.1.3
 - jupyter
 - pip
 - pip:
   - matplotlib-venn==0.11.6
